const Tram = require('tram-one')
const testFighterText = require('./js/actions/testFighterText')
const errorLines = require('./js/actions/errorLines')

const app = new Tram()
app.addRoute('/', require('./pages/home'))
app.addRoute('/404', require('./pages/404'))
app.addRoute('/testPage', require('./pages/testPage'))
app.addRoute('/testPageRyu', require('./pages/testPageRyu'))
app.addRoute('/readerTestPage', require('./pages/ReaderTestPage'))
app.addRoute('/customTextPage', require('./pages/CustomTextPage'))
app.addActions({testFighterText, errorLines})
app.start('.main')
