const Tram = require('tram-one')
const firebase = require('./firebase')
const sideBar = require('./js/actions/sideBar')
const fighterData = require('./js/actions/fighterData')
const testFighterText = require('./js/actions/testFighterText')
const readerActions = require('./js/actions/readerActions')

const app = new Tram()
app.addRoute('/', require('./pages/home'))
app.addRoute('/404', require('./pages/404'))
app.addRoute('/game/:gameId', require('./pages/gamePage'))
app.addRoute('/testPage', require('./pages/testPages/testPage'))
app.addRoute('/testPageRyu', require('./pages/testPages/testPageRyu'))
app.addRoute('/readerTestPage', require('./pages/testPages/ReaderTestPage'))
app.addRoute('/customTextPage', require('./pages/testPages/CustomTextPage'))
app.addActions({testFighterText, reader: readerActions, fighterData, sideBar})
app.start('.main')
