module.exports = {
  'p':{src:'/svgs/punch.svg',alt:"PUNCH"},
  'lp':{src:'/svgs/punch_strength.svg',alt:"LIGHT PUNCH",className:"light",replaceText:[/LP/,'LP']},
  'mp':{src:'/svgs/punch_strength.svg',alt:"MEDIUM PUNCH",className:"medium",replaceText:[/LP/,'MP']},
  'hp':{src:'/svgs/punch_strength.svg',alt:"HEAVY PUNCH",className:"heavy",replaceText:[/LP/,'HP']},
  '2p':{src:'/svgs/punch_2x.svg',alt:"2x PUNCH"},
  '3p':{src:'/svgs/punch_3x.svg',alt:"3x PUNCH"},
  'k':{src:'/svgs/kick.svg',alt:"KICK"},
  'lk':{src:'/svgs/kick_strength.svg',alt:"LIGHT KICK",className:"light",replaceText:[/LK/,'LK']},
  'mk':{src:'/svgs/kick_strength.svg',alt:"MEDIUM KICK",className:"medium",replaceText:[/LK/,'MK']},
  'hk':{src:'/svgs/kick_strength.svg',alt:"HEAVY KICK",className:"heavy",replaceText:[/LK/,'HK']},
  '2k':{src:'/svgs/kick_2x.svg',alt:"2x KICK"},
  '3k':{src:'/svgs/kick_3x.svg',alt:"3x KICK"},
  '1':{src:'/svgs/arrow.svg',alt:"DOWN-BACK",rotate:315},
  'h1':{src:'/svgs/arrow.svg',alt:"DOWN-BACK",className:"hold",rotate:315},
  '2':{src:'/svgs/arrow.svg',alt:"DOWN",rotate:270},
  'c':{src:'/svgs/arrow.svg',alt:"CROUCH",rotate:270},
  'h2':{src:'/svgs/arrow.svg',alt:"DOWN",className:"hold",rotate:270},
  '3':{src:'/svgs/arrow.svg',alt:"DOWN-FORWARD",rotate:225},
  '4':{src:'/svgs/arrow.svg',alt:"BACK"},
  '5':{src:'/svgs/motion.svg',alt:"NEUTRAL"},
  '6':{src:'/svgs/arrow.svg',alt:"FORWARD",rotate:180},
  '7':{src:'/svgs/arrow.svg',alt:"BACK-UP",rotate:45},
  '8':{src:'/svgs/arrow.svg',alt:"UP",rotate:90},
  'j':{src:'/svgs/arrow.svg',alt:"JUMP",rotate:90},
  '9':{src:'/svgs/arrow.svg',alt:"FORWARD-UP",rotate:135},
  '236':{src:'/svgs/qc.svg',alt:"QUARTER CIRCLE FORWARD",className:"flip"},
  '214':{src:'/svgs/qc.svg',alt:"QUARTER CIRCLE BACK",className:""},
  '623':{src:'/svgs/dp.svg',alt:"DRAGON PUNCH FORWARD",className:"flip"},
  '421':{src:'/svgs/dp.svg',alt:"DRAGON PUNCH BACK",className:""},
  '41236':{src:'/svgs/hc.svg',alt:"HALF CIRCLE FORWARD",className:"flip"},
  '63214':{src:'/svgs/hc.svg',alt:"HALF CIRCLE BACK",className:""},
  '63214789':{src:'/svgs/arrow.svg',alt:"360 MOTION BACK",className:"flip"},
  '41236987':{src:'/svgs/arrow.svg',alt:"360 MOTION FORWARD",className:""},
  '(':{src:'/svgs/left_bracket.svg',alt:""},
  ')':{src:'/svgs/left_bracket.svg',alt:"",className:"flip"},
  'cb':{src:'/svgs/custom_button.svg',alt:""},
  'ct':{src:'/svgs/custom_text.svg',alt:""},
  'air':{src:'/svgs/air.svg',alt:""},
}
